apiVersion: v1
kind: Pod
metadata:
  name: app2
  labels:
    name: POD2
    environment: dev
    app: multicontainer
spec:
  containers:
    - name: container-1
      image: ghcr.io/immich-app/immich-server:latest

    - name: container-2
      image: 	plexinc/pms-docker