apiVersion: v1
kind: Pod
metadata:
  name: app-1
  labels:
    name: POD-1
    environment: dev
    app: nginx-hosting
spec:
  containers:
    - name: Container-1
      image: nginx:latest
      ports:
        - containerPort: 80
