apiVersion: v1
kind: Namespace
metadata:
  name: amazondns
  labels:
    app: rc-1
    env: dev
    status: ok
---
apiVersion: v1
kind: ReplicationController
metadata:
  namespace: amazondns
  name: replicationcontrollerdemo #RC-NAME
  labels:
    app: rc-1
    env: dev
    status: ok
spec:
  replicas: 2
  namespace: amazondns
  #selector should match labels.
  selector:
      app: rc-1
      env: dev
      status: ok
  template:
    metadata:
      name: rc-pod-1 #Pod-template
      labels:
        #these lables should match spec.selector
        app: rc-1
        env: dev
        status: ok
    spec:
      containers:
      - name: rc-container-1
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: amazondns
  name: service2
spec:
  selector:
    app: rc-1
    env: dev
    status: ok
  type: LoadBalancer
  ports:
    - name: service2
      protocol: TCP
      port: 80
      targetPort: 80

