apiVersion: v2
kind: service
metadata:
  name: service1
spec:
  selector:
    name: POD1
    environment: dev
    app: nginx-hosting
  type: ClusterIP
  ports:
    - name: service1
      protocol: TCP
      port: 80
      targetPort: 80
