apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    name: POD1
    environment: dev
    app: nginx-hosting
  type: NodePort
  ports:
    - name: service1
      protocol: TCP
      port: 80
      targetPort: 80
